### PR TITLE
Add missing fields to Subkey: Curve, CardNumber and Keygrip

### PR DESCRIPTION
**Pull request by Daniel15**
Tested manually with the `ListKeys` sample... It worked fine:

I really just needed `Keygrip`, but had to add `Curve` and `CardNumber` too, as they're also in the struct.

### CODE REVIEW

**Comment by wget** [comment]
@Daniel15 Ok. Thanks :) I just wanted to know whether having both camel case and underscore based variables was intended?

**Comment by Daniel15** [comment]
>  I just wanted to know whether having both camel case and underscore based variables was intended?

@wget - The name in `Interop/_gpgme_subkey.cs` matches the gpgme C header, whereas the name in `Subkey.cs` uses C# naming standards. This seems to be the pattern in the codebase.

**Comment by wget** [comment]
@Daniel15 Ok. I'm merging this one. But would it be possible to have a new PR to respect the .NET Pascal Case convention (i.e. just camel case beginning with an uppercase letter) for the public API of this library (for the private part, that's of course OK to have underscores if this is easier for interoperability with C code).

**Comment by Daniel15** [comment]
@wget `gpgme_subkey.cs` is just an internal API, it's not exposed publicly.

**Pull request merged**
